### ISSUE TITLE
CUDA error cudaErrorInvalidConfiguration

### ISSUE THREAD

**Issue by kxzhang-lab** [ibaiGorordo/ONNX-CREStereo-Depth-Estimation#2]
When I used command"python driving_stereo_test.py" to run the file driving_stereo_test.py,an error occured as following,so did the file driving_stereo_point_cloud.py.
2022-06-08 08:59:21.161123795 [E:onnxruntime:, sequential_executor.cc:333 Execute] Non-zero status code returned while running Mul node. Name:'Mul_498' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
Traceback (most recent call last):
  File "driving_stereo_test.py", line 55, in <module>
    disparity_map = depth_estimator(left_img, right_img)
  File "/media/fhy/TOSHIBA_EXT/ZKX/ONNX_CREStereo_Depth_Estimation/ONNX-CREStereo-Depth-Estimation-main/crestereo/crestereo.py", line 23, in __call__
    return self.update(left_img, right_img)
  File "/media/fhy/TOSHIBA_EXT/ZKX/ONNX_CREStereo_Depth_Estimation/ONNX-CREStereo-Depth-Estimation-main/crestereo/crestereo.py", line 63, in update
    outputs = self.inference_without_flow(left_tensor, right_tensor)
  File "/media/fhy/TOSHIBA_EXT/ZKX/ONNX_CREStereo_Depth_Estimation/ONNX-CREStereo-Depth-Estimation-main/crestereo/crestereo.py", line 90, in inference_without_flow
    self.input_names[1]: right_tensor})[0]
  File "/home/fhy/anaconda3/envs/CREStereo/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Mul node. Name:'Mul_498' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

**Comment by snehahegdek** [comment]
@15991680709 , Hey any progress here. Even I am facing the same error while using the C API

**Comment by ibaiGorordo** [comment]
That seems to be a deeper problem with the CUDA or ONNX Runtime, especially if you are getting the error also in C API. It might also have to do which I "frankensteined" from the original framework. I guess the same error does not happen with other models (preferably stereo models like HITNET, ACVNET...)?

**Comment by kxzhang-lab** [comment]
thank you.



---- Replied Message ----
| From | Ibai ***@***.***> |
| Date | 07/22/2022 15:39 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [ibaiGorordo/ONNX-CREStereo-Depth-Estimation] CUDA error cudaErrorInvalidConfiguration (Issue #2) |

That seems to be a deeper problem with the CUDA or ONNX Runtime, especially if you are getting the error also in C API. It might also have to do which I "frankensteined" from the original framework. I guess the same error does not happen with other models (preferably stereo models like HITNET, ACVNET...)?
